package org.net9.domain.model.news;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.net9.domain.model.BaseModel;

/**
 * NewsCategory generated by MyEclipse Persistence Tools
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "news_category", uniqueConstraints = {})
public class NewsCategory extends BaseModel implements java.io.Serializable {

	private Integer id;

	private String name;

	private String code;

	private Integer isPlugin = 0;

	private String createTime;

	private String updateTime;

	private Set<NewsEntry> newsEntries = new HashSet<NewsEntry>(0);

	@Column(name = "CODE", unique = false, nullable = false, insertable = true, updatable = true, length = 145)
	public String getCode() {
		return this.code;
	}

	@Column(name = "CREATE_TIME", unique = false, nullable = false, insertable = true, updatable = true, length = 45)
	public String getCreateTime() {
		return this.createTime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "IS_PLUGIN", unique = false, nullable = false)
	public Integer getIsPlugin() {
		return isPlugin;
	}

	@Column(name = "NAME", unique = false, nullable = false, insertable = true, updatable = true, length = 145)
	public String getName() {
		return this.name;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "newsCategory")
	public Set<NewsEntry> getNewsEntries() {
		return this.newsEntries;
	}

	@Column(name = "UPDATE_TIME", unique = false, nullable = false, insertable = true, updatable = true, length = 45)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setIsPlugin(Integer isPlugin) {
		this.isPlugin = isPlugin;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setNewsEntries(Set<NewsEntry> newsEntries) {
		this.newsEntries = newsEntries;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}