package org.net9.domain.model.news;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.net9.domain.model.BaseModel;

import com.j2bb.common.search.Index;

/**
 * NewsEntry generated by MyEclipse Persistence Tools
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "news_entry", uniqueConstraints = {})
public class NewsEntry extends BaseModel implements java.io.Serializable {
	@Index(analyzed=false)
	private Integer id;

	private NewsCategory newsCategory;
	@Index
	private String title;

	private String subtitle;

	private String permalink;

	private String content;
	@Index(analyzed=false)
	private String author;

	private String manager;
	@Index(analyzed=false)
	private Integer hits;

	private String tags;

	private Integer state;
	@Index(analyzed=false)
	private String createTime;
	@Index(analyzed=false)
	private String updateTime;

	private Integer commentFlg;
	private Integer hitGood;

	private Integer hitBad;

	private String fakeUrl;

	@Column(name = "AUTHOR", unique = false, nullable = false, insertable = true, updatable = true, length = 85)
	public String getAuthor() {
		return this.author;
	}

	@Column(name = "COMMENT_FLG", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getCommentFlg() {
		return this.commentFlg;
	}

	@Column(name = "CONTENT", unique = false, nullable = false, insertable = true, updatable = true, length = 65535)
	public String getContent() {
		return this.content;
	}

	@Column(name = "CREATE_TIME", unique = false, nullable = false, insertable = true, updatable = true, length = 45)
	public String getCreateTime() {
		return this.createTime;
	}

	@Column(name = "FAKE_URL", nullable = true, length = 245)
	public String getFakeUrl() {
		return fakeUrl;
	}

	@Column(name = "HIT_BAD", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getHitBad() {
		return this.hitBad;
	}

	@Column(name = "HIT_GOOD", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getHitGood() {
		return this.hitGood;
	}

	@Column(name = "HITS", unique = false, nullable = true, insertable = true, updatable = true)
	public Integer getHits() {
		return this.hits;
	}

	// Property accessors
	@Id
	@Column(name = "ID", unique = true, nullable = false, insertable = true, updatable = true)
	public Integer getId() {
		return this.id;
	}

	@Column(name = "MANAGER", unique = false, nullable = true, insertable = true, updatable = true, length = 85)
	public String getManager() {
		return this.manager;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY_ID", unique = false, nullable = false, insertable = true, updatable = true)
	public NewsCategory getNewsCategory() {
		return this.newsCategory;
	}

	@Column(name = "PERMALINK", unique = false, nullable = true, insertable = true, updatable = true, length = 145)
	public String getPermalink() {
		return this.permalink;
	}

	@Column(name = "STATE", unique = false, nullable = false, insertable = true, updatable = true)
	public Integer getState() {
		return this.state;
	}

	@Column(name = "SUBTITLE", unique = false, nullable = true, insertable = true, updatable = true)
	public String getSubtitle() {
		return this.subtitle;
	}

	@Column(name = "TAGS", unique = false, nullable = true, insertable = true, updatable = true, length = 245)
	public String getTags() {
		return this.tags;
	}

	@Column(name = "TITLE", unique = false, nullable = false, insertable = true, updatable = true, length = 245)
	public String getTitle() {
		return this.title;
	}

	@Column(name = "UPDATE_TIME", unique = false, nullable = false, insertable = true, updatable = true, length = 45)
	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public void setCommentFlg(Integer commentFlg) {
		this.commentFlg = commentFlg;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public void setFakeUrl(String fakeUrl) {
		this.fakeUrl = fakeUrl;
	}

	public void setHitBad(Integer hitBad) {
		this.hitBad = hitBad;
	}

	public void setHitGood(Integer hitGood) {
		this.hitGood = hitGood;
	}

	public void setHits(Integer hits) {
		this.hits = hits;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setManager(String manager) {
		this.manager = manager;
	}

	public void setNewsCategory(NewsCategory newsCategory) {
		this.newsCategory = newsCategory;
	}

	public void setPermalink(String permalink) {
		this.permalink = permalink;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}