package org.net9.domain.model.blog;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.net9.domain.model.BaseModel;

/**
 * BlogCategory generated by MyEclipse Persistence Tools
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "blog_category", uniqueConstraints = {})
public class BlogCategory extends BaseModel implements java.io.Serializable {

	// Fields

	private Integer id;

	private BlogCategory blogCategory;

	private Blog blogBlog;

	private String name;

	private String tags;

	// 2008/04/20
	private Integer idx;

	private Set<BlogCategory> blogCategories = new HashSet<BlogCategory>(0);

	// Constructors

	/** default constructor */
	public BlogCategory() {
	}

	/** minimal constructor */
	public BlogCategory(Integer id, Blog blogBlog, String name, String tags) {
		this.id = id;
		this.blogBlog = blogBlog;
		this.name = name;
		this.tags = tags;
	}

	/** full constructor */
	public BlogCategory(Integer id, BlogCategory blogCategory, Blog blogBlog,
			String name, String tags, Set<BlogCategory> blogCategories) {
		this.id = id;
		this.blogCategory = blogCategory;
		this.blogBlog = blogBlog;
		this.name = name;
		this.tags = tags;
		this.blogCategories = blogCategories;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "blogId", unique = false, nullable = false, insertable = true, updatable = true)
	public Blog getBlogBlog() {
		return this.blogBlog;
	}

	@OneToMany(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY, mappedBy = "blogCategory")
	public Set<BlogCategory> getBlogCategories() {
		return this.blogCategories;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "parentId", unique = false, nullable = true, insertable = true, updatable = true)
	public BlogCategory getBlogCategory() {
		return this.blogCategory;
	}

	// Property accessors
	@Id
	@Column(name = "id", unique = true, nullable = false, insertable = true, updatable = true)
	public Integer getId() {
		return this.id;
	}

	public Integer getIdx() {
		return idx;
	}

	@Column(name = "name", unique = false, nullable = false, insertable = true, updatable = true, length = 50)
	public String getName() {
		return this.name;
	}

	@Column(name = "tags", unique = false, nullable = false, insertable = true, updatable = true, length = 50)
	public String getTags() {
		return this.tags;
	}

	public void setBlogBlog(Blog blogBlog) {
		this.blogBlog = blogBlog;
	}

	public void setBlogCategories(Set<BlogCategory> blogCategories) {
		this.blogCategories = blogCategories;
	}

	public void setBlogCategory(BlogCategory blogCategory) {
		this.blogCategory = blogCategory;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

}